"""budgets, debts and loans

Revision ID: 575bb98c6caa
Revises: 5e47c5199a2c
Create Date: 2026-08-24 17:25:11.029983
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '575bb98c6caa'
down_revision: Union[str, None] = '5e47c5199a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('CATEGORY', 'FLOW', name='budgetkind', native_enum=False, length=16), nullable=False),
    sa.Column('target', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_budgets_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('book_id', 'kind', 'target', name='uq_budget_target')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_book_id'), ['book_id'], unique=False)

    op.create_table('debts',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('person', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.Enum('OWED_TO_ME', 'I_OWE', name='direction', native_enum=False, length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_debts_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_debts'))
    )
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.create_index('ix_debts_open', ['book_id', 'settled_at'], unique=False)

    op.create_table('loans',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_loans_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index('ix_loans_book', ['book_id', 'is_active'], unique=False)

    op.create_table('loan_payments',
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], name=op.f('fk_loan_payments_loan_id_loans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_loan_payments_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_payments'))
    )
    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.create_index('ix_loan_payments_loan', ['loan_id'], unique=False)

    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('treasury_percent',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('debit',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('credit',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('distributable_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('share_value_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('base_share',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('adjustments_total',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('net_pay',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('performance_records', schema=None) as batch_op:
        batch_op.alter_column('hours_worked',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('days_worked',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('absence_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('mission_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('late_count',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('points',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('original_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('converted_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('value_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.alter_column('value_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('converted_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('original_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('performance_records', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('late_count',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('mission_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('absence_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('overtime_hours',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('days_worked',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('hours_worked',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('net_pay',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('adjustments_total',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('base_share',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('share_value_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('distributable_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.alter_column('conversion_rate',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('treasury_percent',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_loan_payments_loan')

    op.drop_table('loan_payments')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('ix_loans_book')

    op.drop_table('loans')
    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.drop_index('ix_debts_open')

    op.drop_table('debts')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_book_id'))

    op.drop_table('budgets')
    # ### end Alembic commands ###
