"""initial schema

Revision ID: 5e47c5199a2c
Revises: 
Create Date: 2026-08-24 16:14:12.293095
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e47c5199a2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('audit_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_user_action', ['user_id', 'action'], unique=False)

    op.create_table('books',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('PERSONAL', 'BUSINESS', 'TEAM', 'ORGANIZATION', name='booktype', native_enum=False, length=16), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('calendar', sa.String(length=16), nullable=False),
    sa.Column('treasury_percent', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_books_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('ix_books_owner', ['owner_user_id'], unique=False)

    op.create_table('identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('WEB', 'TELEGRAM', 'BALE', 'RUBIKA', 'EITAA', name='provider', native_enum=False, length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_username', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identities')),
    sa.UniqueConstraint('provider', 'external_id', name='one_account_per_external_identity')
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index('ix_identities_user', ['user_id'], unique=False)

    op.create_table('link_tokens',
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.Enum('FROM_WEB', 'FROM_MESSENGER', name='linkdirection', native_enum=False, length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Enum('WEB', 'TELEGRAM', 'BALE', 'RUBIKA', 'EITAA', name='provider', native_enum=False, length=16), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('external_username', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_link_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_tokens'))
    )
    with op.batch_alter_table('link_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_link_tokens_digest', ['token_digest'], unique=True)
        batch_op.create_index('ix_link_tokens_user', ['user_id'], unique=False)

    op.create_table('accounts',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype', native_enum=False, length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_accounts_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('book_id', 'code', name='one_account_code_per_book')
    )
    op.create_table('financial_periods',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CALCULATING', 'AWAITING_APPROVAL', 'APPROVED', 'PAID', 'LOCKED', name='periodstatus', native_enum=False, length=20), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_financial_periods_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_periods')),
    sa.UniqueConstraint('book_id', 'label', name='one_period_label_per_book')
    )
    with op.batch_alter_table('financial_periods', schema=None) as batch_op:
        batch_op.create_index('ix_periods_book_status', ['book_id', 'status'], unique=False)

    op.create_table('memberships',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ACCOUNTANT', 'MEMBER', 'VIEWER', name='role', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_memberships_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('book_id', 'user_id', name='one_membership_per_user_per_book')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_memberships_user', ['user_id'], unique=False)

    op.create_table('share_rules',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('basis', sa.Enum('PERCENT', 'FIXED', 'HOURS', 'DAYS', 'POINTS', 'PROJECT', name='sharebasis', native_enum=False, length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_share_rules_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_share_rules_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_rules'))
    )
    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.create_index('ix_share_rules_book_user', ['book_id', 'user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('flow', sa.Enum('INCOME', 'EXPENSE', name='flow', native_enum=False, length=12), nullable=False),
    sa.Column('scope', sa.Enum('WORK', 'PERSONAL', 'TEAM', name='scope', native_enum=False, length=12), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('original_currency', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('converted_amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('rate_source', sa.String(length=40), nullable=True),
    sa.Column('rate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_mode', sa.Enum('AUTOMATIC', 'MANUAL', name='ratemode', native_enum=False, length=12), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_transactions_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_transactions_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_tx_book_date', ['book_id', 'occurred_on'], unique=False)
        batch_op.create_index('ix_tx_book_flow_date', ['book_id', 'flow', 'occurred_on'], unique=False)

    op.create_table('treasury_funds',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('MAIN', 'EMERGENCY', 'TAX', 'DEVELOPMENT', 'EQUIPMENT', 'BONUS', name='fundkind', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_treasury_funds_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treasury_funds')),
    sa.UniqueConstraint('book_id', 'kind', name='one_fund_of_each_kind_per_book')
    )
    op.create_table('adjustments',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('BONUS', 'OVERTIME', 'PENALTY', 'SHORTFALL', 'ADVANCE', 'CORRECTION', name='adjustmentkind', native_enum=False, length=16), nullable=False),
    sa.Column('mode', sa.Enum('PERCENT', 'AMOUNT', name='adjustmentmode', native_enum=False, length=12), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_adjustments_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_adjustments_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], name=op.f('fk_adjustments_period_id_financial_periods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_adjustments_recorded_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_adjustments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustments'))
    )
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.create_index('ix_adjustments_period_user', ['period_id', 'user_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_journal_entries_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_journal_entries_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('ix_journal_book_date', ['book_id', 'occurred_on'], unique=False)

    op.create_table('payslips',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('distributable_snapshot', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('share_basis_snapshot', sa.Enum('PERCENT', 'FIXED', 'HOURS', 'DAYS', 'POINTS', 'PROJECT', name='sharebasis', native_enum=False, length=16), nullable=False),
    sa.Column('share_value_snapshot', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('base_share', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('adjustments_total', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_payslips_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], name=op.f('fk_payslips_period_id_financial_periods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payslips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips')),
    sa.UniqueConstraint('period_id', 'user_id', name='one_payslip_per_member_per_period')
    )
    op.create_table('performance_records',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('days_worked', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('absence_days', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('leave_days', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('mission_days', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('late_count', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('points', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_performance_records_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], name=op.f('fk_performance_records_period_id_financial_periods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_performance_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_records')),
    sa.UniqueConstraint('period_id', 'user_id', name='one_record_per_member_per_period')
    )
    op.create_table('treasury_allocations',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('fund_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('basis_snapshot', sa.Enum('GROSS_PERCENT', 'NET_PERCENT', 'FIXED', name='rulebasis', native_enum=False, length=20), nullable=False),
    sa.Column('value_snapshot', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_treasury_allocations_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fund_id'], ['treasury_funds.id'], name=op.f('fk_treasury_allocations_fund_id_treasury_funds'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], name=op.f('fk_treasury_allocations_period_id_financial_periods'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treasury_allocations'))
    )
    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.create_index('ix_alloc_period', ['period_id'], unique=False)

    op.create_table('treasury_rules',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('fund_id', sa.Uuid(), nullable=False),
    sa.Column('basis', sa.Enum('GROSS_PERCENT', 'NET_PERCENT', 'FIXED', name='rulebasis', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_treasury_rules_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fund_id'], ['treasury_funds.id'], name=op.f('fk_treasury_rules_fund_id_treasury_funds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treasury_rules'))
    )
    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.create_index('ix_treasury_rules_book', ['book_id', 'is_active'], unique=False)

    op.create_table('journal_lines',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('credit', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_journal_lines_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], name=op.f('fk_journal_lines_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines'))
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index('ix_journal_lines_account', ['account_id'], unique=False)

    op.create_table('payroll_payments',
    sa.Column('payslip_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], name=op.f('fk_payroll_payments_payslip_id_payslips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_payments'))
    )
    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_payslip', ['payslip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_payslip')

    op.drop_table('payroll_payments')
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_lines_account')

    op.drop_table('journal_lines')
    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_treasury_rules_book')

    op.drop_table('treasury_rules')
    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.drop_index('ix_alloc_period')

    op.drop_table('treasury_allocations')
    op.drop_table('performance_records')
    op.drop_table('payslips')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_book_date')

    op.drop_table('journal_entries')
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.drop_index('ix_adjustments_period_user')

    op.drop_table('adjustments')
    op.drop_table('treasury_funds')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_book_flow_date')
        batch_op.drop_index('ix_tx_book_date')

    op.drop_table('transactions')
    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_share_rules_book_user')

    op.drop_table('share_rules')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_memberships_user')

    op.drop_table('memberships')
    with op.batch_alter_table('financial_periods', schema=None) as batch_op:
        batch_op.drop_index('ix_periods_book_status')

    op.drop_table('financial_periods')
    op.drop_table('accounts')
    with op.batch_alter_table('link_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_link_tokens_user')
        batch_op.drop_index('ix_link_tokens_digest')

    op.drop_table('link_tokens')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index('ix_identities_user')

    op.drop_table('identities')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('ix_books_owner')

    op.drop_table('books')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_action')

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
