"""A book may hold several currencies, and move value between them.

`book_currencies` lists the currencies a book is allowed to hold beyond its
base one. The base currency is deliberately not a row: it is always allowed,
which is why this migration needs no backfill for the books that already
exist, and why no one can switch it off.

`currency_conversions` records a swap between two of those currencies. It is
not a transaction table on purpose — payroll decides what everyone is paid by
summing income and expense, and a conversion is neither.

Both tables are new, so their NOT NULL columns need no server default; there
are no rows to default.

Revision ID: 9e632756c0e3
Revises: ef1aef99404
Create Date: 2026-09-20 12:10:09.844951
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e632756c0e3'
down_revision: Union[str, None] = 'ef1aef99404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_currencies',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_currencies_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_currencies')),
    sa.UniqueConstraint('book_id', 'code', name='one_row_per_currency_per_book')
    )
    op.create_table('currency_conversions',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('from_currency', sa.String(length=8), nullable=False),
    sa.Column('from_amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('to_currency', sa.String(length=8), nullable=False),
    sa.Column('to_amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('base_value', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_currency_conversions_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_currency_conversions_book_id_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_currency_conversions'))
    )
    with op.batch_alter_table('currency_conversions', schema=None) as batch_op:
        batch_op.create_index('ix_conversions_book_day', ['book_id', 'occurred_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_conversions', schema=None) as batch_op:
        batch_op.drop_index('ix_conversions_book_day')

    op.drop_table('currency_conversions')
    op.drop_table('book_currencies')
    # ### end Alembic commands ###
