"""notification preferences

Every column carries a server_default. Adding a NOT NULL column to a table
that already has rows fails on PostgreSQL without one — SQLite hides this,
because batch mode rebuilds the table and applies the Python-side default.

Revision ID: a1a1e98e89f1
Revises: c2f358636dfb
Create Date: 2026-08-24 18:14:54.007395
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a1a1e98e89f1'
down_revision: Union[str, None] = 'c2f358636dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('treasury_percent',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('debit',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('credit',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('installment_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('distributable_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('share_value_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('base_share',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('adjustments_total',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('net_pay',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('performance_records', schema=None) as batch_op:
        batch_op.alter_column('hours_worked',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('days_worked',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('absence_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('mission_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('late_count',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('points',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('original_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('converted_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('value_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digest_enabled', sa.Boolean(), nullable=False,
                            server_default=sa.true()))
        batch_op.add_column(sa.Column('digest_hour', sa.Integer(), nullable=False,
                            server_default='21'))
        batch_op.add_column(sa.Column('reminder_days', sa.Integer(), nullable=False,
                            server_default='3'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reminder_days')
        batch_op.drop_column('digest_hour')
        batch_op.drop_column('digest_enabled')

    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.alter_column('value_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('converted_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('original_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('performance_records', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('late_count',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('mission_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('absence_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('overtime_hours',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('days_worked',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('hours_worked',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('net_pay',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('adjustments_total',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('base_share',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('share_value_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('distributable_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.alter_column('conversion_rate',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('installment_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('treasury_percent',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###
