"""recurring rules and receipts

Revision ID: c2f358636dfb
Revises: 575bb98c6caa
Create Date: 2026-08-24 18:01:17.437373
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2f358636dfb'
down_revision: Union[str, None] = '575bb98c6caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_rules',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('flow', sa.Enum('INCOME', 'EXPENSE', name='flow', native_enum=False, length=16), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='period', native_enum=False, length=16), nullable=False),
    sa.Column('next_run_on', sa.Date(), nullable=False),
    sa.Column('last_run_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_recurring_rules_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_recurring_rules_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurring_rules'))
    )
    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.create_index('ix_recurring_due', ['is_active', 'next_run_on'], unique=False)

    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('treasury_percent',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('debit',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('credit',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('installment_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('distributable_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('share_value_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('base_share',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('adjustments_total',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('net_pay',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('performance_records', schema=None) as batch_op:
        batch_op.alter_column('hours_worked',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('days_worked',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('overtime_hours',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('absence_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('mission_days',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('late_count',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('points',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_file_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('receipt_provider', sa.String(length=16), nullable=True))
        batch_op.alter_column('original_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('converted_amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('value_snapshot',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=28, scale=4),
               type_=sa.Numeric(precision=28, scale=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treasury_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('treasury_allocations', schema=None) as batch_op:
        batch_op.alter_column('value_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('converted_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('conversion_rate',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('original_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.drop_column('receipt_provider')
        batch_op.drop_column('receipt_file_id')

    with op.batch_alter_table('share_rules', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('performance_records', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('late_count',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('mission_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('leave_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('absence_days',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('overtime_hours',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('days_worked',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('hours_worked',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.alter_column('net_pay',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('adjustments_total',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('base_share',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('share_value_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('distributable_snapshot',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('payroll_payments', schema=None) as batch_op:
        batch_op.alter_column('conversion_rate',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.alter_column('installment_amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('debts', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('treasury_percent',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Numeric(precision=28, scale=4),
               type_=sa.NUMERIC(precision=28, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('recurring_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_recurring_due')

    op.drop_table('recurring_rules')
    # ### end Alembic commands ###
