#!/bin/bash
# Install KasbBook from nothing.
#
# Idempotent: running it twice is safe and the second run repairs whatever the
# first one left half-done. It asks for the few things it genuinely cannot
# invent — a bot token — and generates everything it can, because a signing key
# somebody types by hand is a signing key somebody can guess.

source "$(dirname "$(readlink -f "$0")")/lib.sh" 2>/dev/null || {
    # Bootstrapping from a bare curl, before the repo exists.
    set -euo pipefail
    KASBBOOK_HOME="${KASBBOOK_HOME:-/opt/kasbbook-v2}"
    KASBBOOK_BRANCH="${KASBBOOK_BRANCH:-main}"
    KASBBOOK_REPO="${KASBBOOK_REPO:-https://github.com/Emadhabibnia1385/KasbBook.git}"
    R=$'\033[31m'; G=$'\033[32m'; Y=$'\033[33m'; C=$'\033[36m'; N=$'\033[0m'
    say()  { echo "${C}==>${N} $*"; }
    ok()   { echo "  ${G}✓${N} $*"; }
    warn() { echo "  ${Y}!${N} $*"; }
    die()  { echo "  ${R}✗${N} $*" >&2; exit 1; }
    UNITS=(kasbbook-bot kasbbook-api)
}

[ "$(id -u)" -eq 0 ] || die "run this with sudo"

say "checking what this box already has"
for tool in git python3 curl; do
    command -v "$tool" >/dev/null || die "$tool is required and not installed"
done
PYTHON_OK="$(python3 -c 'import sys; print(1 if sys.version_info >= (3, 11) else 0)')"
[ "$PYTHON_OK" = "1" ] || die "python3.11 or newer is required (found $(python3 -V))"
ok "python $(python3 -V | cut -d' ' -f2)"

command -v docker >/dev/null && ok "docker is available" || warn "no docker — you will need your own PostgreSQL and Redis"

say "fetching the code into $KASBBOOK_HOME"
if [ -d "$KASBBOOK_HOME/.git" ]; then
    git config --global --add safe.directory "$KASBBOOK_HOME" 2>/dev/null || true
    git -C "$KASBBOOK_HOME" fetch --quiet origin "$KASBBOOK_BRANCH"
    # Move the local branch too, not just its contents. Resetting alone leaves
    # HEAD on whatever branch it was on — an install from before the release
    # sits on `v2`, and would keep reporting that name while holding main's
    # code. `git status` lying about which branch you are on is a bad way to
    # start debugging anything.
    git -C "$KASBBOOK_HOME" checkout --quiet -B "$KASBBOOK_BRANCH" \
        "origin/$KASBBOOK_BRANCH"
else
    git clone --quiet --branch "$KASBBOOK_BRANCH" "$KASBBOOK_REPO" "$KASBBOOK_HOME"
    git config --global --add safe.directory "$KASBBOOK_HOME" 2>/dev/null || true
fi
cd "$KASBBOOK_HOME"
ok "$(git log --oneline -1)"

say "python environment"
[ -d venv ] || python3 -m venv venv
./venv/bin/pip install --quiet --upgrade pip
./venv/bin/pip install --quiet -r requirements-v2.txt
# Editable, so `kasbbook` is importable because it is installed rather than
# because something arranged sys.path first. That arrangement has broken three
# times, most recently under uvicorn.
./venv/bin/pip install --quiet --no-deps -e .
ok "dependencies installed"

# ---------------------------------------------------------------- datastores
if [ ! -f deploy/.env ]; then
    say "generating datastore credentials"
    POSTGRES_PASSWORD="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
    cat > deploy/.env <<ENV
POSTGRES_DB=kasbbook
POSTGRES_USER=kasbbook
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_PORT=5435
REDIS_PORT=6382
ENV
    chmod 600 deploy/.env
    ok "written to deploy/.env"
fi

if command -v docker >/dev/null; then
    say "starting PostgreSQL and Redis"
    (cd deploy && docker compose up -d) >/dev/null 2>&1 || warn "compose did not start cleanly"

    # A container that is "up" is not a database that accepts connections.
    for _ in $(seq 1 30); do
        (cd deploy && docker compose exec -T postgres pg_isready -q) 2>/dev/null && break
        sleep 2
    done
    (cd deploy && docker compose exec -T postgres pg_isready -q) 2>/dev/null \
        && ok "postgres is accepting connections" \
        || warn "postgres is not answering yet; check 'docker compose -f deploy/docker-compose.yml logs'"
fi

# -------------------------------------------------------------- environment
if [ ! -f .env ]; then
    say "setting up the environment"
    . deploy/.env 2>/dev/null || true

    echo
    read -r -p "  Telegram bot token (from @BotFather): " TOKEN
    [ -n "$TOKEN" ] || die "a bot token is required"
    read -r -p "  Bot username, without the @: " USERNAME

    cat > .env <<ENV
# Generated by scripts/install.sh. Secrets live here and nowhere else.

KASBBOOK_PROVIDER=telegram
TELEGRAM_BOT_TOKEN=$TOKEN
TELEGRAM_BOT_USERNAME=${USERNAME#@}

KASBBOOK_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-kasbbook}:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT:-5435}/${POSTGRES_DB:-kasbbook}
REDIS_URL=redis://127.0.0.1:${REDIS_PORT:-6382}/0

# Generated, never typed: a signing key a person chose is a key a person can guess.
KASBBOOK_SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')
KASBBOOK_ACCESS_MINUTES=30
KASBBOOK_REFRESH_DAYS=30

KASBBOOK_LOG_LEVEL=INFO
ENV
    chmod 600 .env
    ok "written to .env"
else
    ok ".env already exists; leaving it alone"
    # An installation predating the API has no signing key, and the API will
    # not start without one. Adding it is safe; overwriting it would sign
    # everyone out.
    if ! grep -q "^KASBBOOK_SECRET_KEY=" .env; then
        echo "KASBBOOK_SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')" >> .env
        ok "added a signing key for the API"
    fi
fi

say "creating the schema"
set -a; . ./.env; set +a
./venv/bin/alembic upgrade head
ok "schema at $(./venv/bin/alembic current 2>/dev/null | tail -1)"

# The first deployment ran under a single unit called kasbbook-v2, whose
# ExecStart pointed at apps/telegram_bot/runner.py. That path no longer exists
# and there are now two units, so the old one is retired here rather than left
# to fail quietly beside the new ones.
if [ -f /etc/systemd/system/kasbbook-v2.service ]; then
    say "retiring the old kasbbook-v2 unit"
    systemctl disable --quiet --now kasbbook-v2 2>/dev/null || true
    rm -f /etc/systemd/system/kasbbook-v2.service
    systemctl daemon-reload
    ok "replaced by kasbbook-bot and kasbbook-api"
fi

say "installing services"
for unit in "${UNITS[@]}"; do
    install -m 644 "deploy/$unit.service" "/etc/systemd/system/$unit.service"
done
systemctl daemon-reload
systemctl enable --quiet --now kasbbook-bot
systemctl enable --quiet --now kasbbook-api

say "health"
sleep 10
FAILED=0
for unit in "${UNITS[@]}"; do
    if systemctl is-active --quiet "$unit"; then
        ok "$unit is running"
    else
        warn "$unit did not start:"
        journalctl -u "$unit" -n 15 --no-pager -o cat | sed 's/^/      /'
        FAILED=1
    fi
done

curl -fsS --max-time 5 http://127.0.0.1:8210/readyz >/dev/null 2>&1 \
    && ok "the API answers /readyz" \
    || warn "the API is not answering on 127.0.0.1:8210 yet"

echo
if [ "$FAILED" = 0 ]; then
    ok "KasbBook is installed and running."
    echo
    echo "  bot logs:   journalctl -u kasbbook-bot -f"
    echo "  api logs:   journalctl -u kasbbook-api -f"
    echo "  api docs:   http://127.0.0.1:8210/docs"
    echo "  update:     sudo $KASBBOOK_HOME/scripts/update.sh"
    echo "  backup:     sudo $KASBBOOK_HOME/scripts/backup.sh"
else
    die "installation finished with problems; see the logs above"
fi
