#!/bin/bash
# Add, list or remove a second messenger.
#
# One process runs one provider. A Bale bot is therefore a third unit beside
# the Telegram bot and the API, with its own token and its own environment
# file — never one process holding two identities. Everything else is shared:
# the same database, so an account linked to both messengers is one set of
# books, which is the whole point of the identity model.
#
#   sudo scripts/messenger.sh add bale
#   sudo scripts/messenger.sh list
#   sudo scripts/messenger.sh remove rubika

source "$(dirname "$(readlink -f "$0")")/lib.sh"

usage() {
    cat <<USAGE
  usage: messenger.sh <add|list|remove> [provider]

    add <provider>      ask for a token, write the unit, start it
    list                which messengers this box runs
    remove <provider>   stop and delete one; the account links it made stay

  providers: ${EXTRA_PROVIDERS[*]}
USAGE
}

valid_provider() {
    local p
    for p in "${EXTRA_PROVIDERS[@]}"; do [ "$p" = "$1" ] && return 0; done
    return 1
}

list_messengers() {
    say "messengers on this box"
    local main_user
    main_user=$(env_value TELEGRAM_BOT_USERNAME)
    printf "  %-10s %-22s %s\n" "telegram" "@${main_user:-?}" "$(systemctl is-active kasbbook-bot 2>/dev/null)"
    local p user
    for p in $(installed_providers); do
        user=$(env_value "$(echo "$p" | tr '[:lower:]' '[:upper:]')_BOT_USERNAME" "$KASBBOOK_HOME/.env.$p")
        printf "  %-10s %-22s %s\n" "$p" "@${user:-?}" "$(systemctl is-active "kasbbook-$p" 2>/dev/null)"
    done
}

add_messenger() {
    local provider="$1" upper unit env_file
    valid_provider "$provider" || die "unknown provider '$provider' — one of: ${EXTRA_PROVIDERS[*]}"
    upper=$(echo "$provider" | tr '[:lower:]' '[:upper:]')
    unit="kasbbook-$provider"
    env_file="$KASBBOOK_HOME/.env.$provider"

    [ -f "$KASBBOOK_HOME/.env" ] || die "$KASBBOOK_HOME/.env is missing — run install.sh first"

    if [ -f "$env_file" ]; then
        warn "$env_file already exists; leaving its token alone"
    else
        say "setting up $provider"
        echo
        # Indirect expansion rather than eval: the value came from a person or
        # the environment, and running it as code is exactly the mistake the
        # installer already made once.
        local token_var="${upper}_BOT_TOKEN" user_var="${upper}_BOT_USERNAME"
        local token username

        ask "$token_var" "  $provider bot token: "
        token=${!token_var:-}
        [ -n "$token" ] || die "a token is required. Either run this from a terminal, \
or pass it: sudo $token_var=... scripts/messenger.sh add $provider"
        sane "$token" "$token_var"

        ask "$user_var" "  $provider bot username, without the @: "
        username=${!user_var:-}
        username=${username#@}
        sane "$username" "$user_var"

        # Only what differs. The database URL, Redis and the signing key stay
        # in the shared .env and are loaded first by the unit — so rotating
        # the key is one edit rather than one per messenger.
        cat > "$env_file" <<ENV
# Generated by scripts/messenger.sh. Loaded after $KASBBOOK_HOME/.env, so it
# only needs to carry what is different about this messenger.

KASBBOOK_PROVIDER=$provider
${upper}_BOT_TOKEN=$token
${upper}_BOT_USERNAME=$username
ENV
        chmod 600 "$env_file"
        ok "written to $env_file"
    fi

    say "unit"
    write_provider_unit "$provider"
    systemctl daemon-reload
    ok "/etc/systemd/system/$unit.service"

    say "starting"
    systemctl enable --quiet --now "$unit"

    say "health"
    if service_is_healthy "$unit" 10; then
        ok "$unit: active, log clean"
        ok "$provider is running. It shares the database, so an account linked to"
        echo "      both messengers is one set of books."
    else
        show_failure "$unit"
        die "$provider did not come up. Its token is in $env_file; nothing else was changed."
    fi
}

remove_messenger() {
    local provider="$1" unit
    valid_provider "$provider" || die "unknown provider '$provider' — one of: ${EXTRA_PROVIDERS[*]}"
    unit="kasbbook-$provider"
    [ -f "/etc/systemd/system/$unit.service" ] || die "$provider is not installed"

    warn "this stops and deletes the $provider bot."
    echo "      Accounts linked through it keep their books; they just lose that way in."
    confirm "$provider" "Type '$provider' to go ahead: "

    systemctl disable --quiet --now "$unit" 2>/dev/null || true
    rm -f "/etc/systemd/system/$unit.service"
    systemctl daemon-reload
    ok "unit removed"

    # The token is left behind on purpose. Deleting it turns "I removed the
    # wrong one" from a restart into a trip back to BotFather.
    if [ -f "$KASBBOOK_HOME/.env.$provider" ]; then
        ok "$KASBBOOK_HOME/.env.$provider kept — delete it yourself if the token is finished with"
    fi
}

# need_root per branch, not up front: somebody typing the command to find out
# what it does should be told, not refused.
case "${1:-}" in
    add)    need_root; [ -n "${2:-}" ] || { usage; exit 1; }; add_messenger "$2" ;;
    remove) need_root; [ -n "${2:-}" ] || { usage; exit 1; }; remove_messenger "$2" ;;
    list)   need_root; list_messengers ;;
    *)      usage ;;
esac
