"""KasbBook — a Telegram bookkeeping bot for small businesses.

This re-exports the public surface of every submodule, so callers and
tests can reach any of it from one place while the code itself stays
split by responsibility.
"""

from .access import access_allowed, denied_text, deny, is_admin, is_primary_admin, resolve_scope_owner, within_quota
from .app import build_app, main
from .backups import backup_job, db_menu_kb, db_menu_text, db_target_kb, schedule_backup_job, send_backup_file
from .budgets import budget_status, budget_warning, budgets_kb, budgets_text, delete_budget, list_budgets, set_budget
from .categories import build_cat_kb, cat_pick_keyboard, ensure_installment, fetch_cats, find_categories_by_name
from .config import ACCESS_ADMIN_ONLY, ACCESS_PUBLIC, ADMIN_CHAT_ID, ADMIN_CHAT_ID_RAW, ADMIN_PAGE_SIZE, ADMIN_USERNAME, ADMIN_USERNAME_RAW, BACKUP_DIR, BOT_TOKEN, BUDGET_PAGE_SIZE, CAT_PAGE_SIZE, CB_AC, CB_AD, CB_BG, CB_CT, CB_CU, CB_DB, CB_DL, CB_DT, CB_DTX, CB_LN, CB_M, CB_RC, CB_RM, CB_RP, CB_SR, CB_ST, CB_TR, CB_TX, DAILY_PAGE_SIZE, DB_LOCK, DB_PATH, DEBT_PAGE_SIZE, DEFAULT_CURRENCY, INSTALLMENT_NAME, JOB_BACKUP, JOB_DIGEST, JOB_RECURRING, LOAN_PAGE_SIZE, PRIMARY_ADMIN_USER_ID, PRIMARY_ADMIN_USER_ID_RAW, PROJECT_NAME, PUBLIC_MAX_CATEGORIES, PUBLIC_MAX_TX_PER_DAY, RLM, SEARCH_PAGE_SIZE, TOP_CATEGORIES, TZ, ZWSP, logger
from .debts import DEBT_LABELS, create_debt, debt_totals, debts_kb, debts_text, delete_debt, list_debts, settle_debt
from .handlers.admin import adm_add_name, adm_add_uid, admin_panel_cb, build_admin_panel_kb
from .handlers.categories import cat_add_name, cat_rename_name, cats_cb
from .handlers.common import access_cb, cancel_cmd, main_cb, on_error, settings_cb, setup_commands, start, unknown_callback
from .handlers.database import currency_cb, currency_custom_input, db_cb, db_interval_entry, db_restore_entry, db_restore_wait_doc, db_set_interval_input, db_set_target_id_input, db_target_choice_cb, reminder_days_input, reminder_hour_input, reminders_cb
from .handlers.finance import budget_amount_input, budget_catname_input, budget_pick_kb, budgets_cb, debt_amount_input, debt_dir_cb, debt_dir_kb, debt_due_input, debt_due_skip, debt_note_input, debt_note_skip, debt_person_input, debts_cb, loan_amount_input, loan_count_input, loan_start_input, loan_title_input, loans_cb, rc_amount_input, rc_cat_input, rc_desc_input, rc_desc_skip, rc_period_cb, rc_period_kb, rc_start_input, rc_ttype_cb, rc_ttype_kb, recurring_cb
from .handlers.quick import parse_quick_entry, quick_entry, quick_entry_cb, quick_group_kb, save_quick_entry
from .handlers.reports import range_end_input, range_entry, range_start_input, report_cb, report_root, search_entry, search_page_cb, search_query_input, show_search_results, trend_cb
from .handlers.transactions import apply_tx_date, daily_cb, dl_date_g_input, dl_date_j_input, dtx_cb, edit_amount_input, edit_date_g_input, edit_date_j_input, edit_date_menu_cb, edit_desc_input, finalize_tx, receipt_wait, tx_amount_input, tx_cat_add_name_input, tx_cat_pick_cb, tx_date_g_input, tx_date_j_input, tx_date_menu_cb, tx_desc_input, tx_desc_skip, tx_entry_from_daily, tx_entry_from_menu, tx_ttype_cb
from .jalali import JMONTHS, add_jalali_months, g_to_j, g_to_j_parts, j_month_range_g, j_to_g_str, j_year_range_g, jmonth_name, week_range_g
from .ledger import SECTION_ORDER, TX_SNAPSHOT_FIELDS, count_transactions, current_pages, daily_back_cb, daily_list_text, daily_rows_kb, ed_date_menu_kb, get_tx, normalize_pages, remember_pages, restore_tx, set_receipt, snapshot_tx, sums_all, sums_for_range, tx_cat_change_kb, tx_detail_text, tx_view_kb
from .loans import create_loan, delete_loan, get_loan, list_loans, loan_detail_kb, loan_detail_text, loan_due_dates, loan_progress, loans_kb, loans_text, next_unpaid_due, record_loan_payment
from .menus import access_menu, cats_root_menu, daily_pick_menu, main_menu, settings_menu, start_text, tx_date_menu_kb, tx_menu, tx_ttype_kb
from .money import currency, currency_kb, fmt_money
from .parsing import parse_amount, parse_date_any, parse_gregorian, parse_jalali_to_g, to_ascii_digits
from .recurring import PERIOD_LABELS, create_recurring, delete_recurring, list_recurring, next_run_after, recurring_job, recurring_kb, recurring_text, run_due_recurring, schedule_recurring_job, toggle_recurring
from .reminders import digest_job, digest_text, reminders_kb, reminders_text, schedule_digest_job, upcoming_loan_reminders
from .reports import TREND_METRICS, back_to_period_kb, breakdown_text, category_breakdown, comparison_lines, csv_filename, jalali_years_with_data, make_csv_bytes, monthly_trend, parse_period, period_extra_kb, previous_period, range_report_kb, report_lines, report_month_kb, report_root_kb, report_year_kb, search_results_kb, search_results_text, search_transactions, trend_kb, trend_text
from .states import ADM_ADD_NAME, ADM_ADD_UID, BG_AMOUNT, BG_CATNAME, BG_PICK, CAT_ADD_NAME, CAT_RENAME_NAME, CU_CUSTOM, DB_RESTORE_WAIT_DOC, DB_SET_INTERVAL, DB_SET_TARGET_ID, DL_DATE_G, DL_DATE_J, DL_DATE_MENU, DT_AMOUNT, DT_DIR, DT_DUE, DT_NOTE, DT_PERSON, ED_AMOUNT, ED_DATE_G, ED_DATE_J, ED_DATE_MENU, ED_DESC, LN_AMOUNT, LN_COUNT, LN_START, LN_TITLE, RCP_WAIT, RC_AMOUNT, RC_CAT, RC_DESC, RC_PERIOD, RC_START, RC_TTYPE, RG_END, RG_START, RM_DAYS, RM_HOUR, SR_QUERY, TX_AMOUNT, TX_CAT_ADD_NAME, TX_CAT_PICK, TX_DATE_G, TX_DATE_J, TX_DATE_MENU, TX_DESC, TX_TTYPE
from .store import BASE_SCHEMA, MIGRATIONS, SCHEMA_VERSION, backup_filename, db, db_conn, db_sidecars, drop_sidecars, get_setting, init_db, make_backup_bytes, save_disk_backup, set_setting, validate_backup_file
from .text import fmt_num, grp_label, ikb, page_nav_row, rtl, safe_edit, ttype_label
from .timeutil import now_ts, today_g
from .store import (
    _INSTALLMENT_READY, _SETTINGS_CACHE, _columns, _detect_version,
    _table_exists, _table_sql,
)

__all__ = [
    "ACCESS_ADMIN_ONLY",
    "ACCESS_PUBLIC",
    "ADMIN_CHAT_ID",
    "ADMIN_CHAT_ID_RAW",
    "ADMIN_PAGE_SIZE",
    "ADMIN_USERNAME",
    "ADMIN_USERNAME_RAW",
    "ADM_ADD_NAME",
    "ADM_ADD_UID",
    "BACKUP_DIR",
    "BASE_SCHEMA",
    "BG_AMOUNT",
    "BG_CATNAME",
    "BG_PICK",
    "BOT_TOKEN",
    "BUDGET_PAGE_SIZE",
    "CAT_ADD_NAME",
    "CAT_PAGE_SIZE",
    "CAT_RENAME_NAME",
    "CB_AC",
    "CB_AD",
    "CB_BG",
    "CB_CT",
    "CB_CU",
    "CB_DB",
    "CB_DL",
    "CB_DT",
    "CB_DTX",
    "CB_LN",
    "CB_M",
    "CB_RC",
    "CB_RM",
    "CB_RP",
    "CB_SR",
    "CB_ST",
    "CB_TR",
    "CB_TX",
    "CU_CUSTOM",
    "DAILY_PAGE_SIZE",
    "DB_LOCK",
    "DB_PATH",
    "DB_RESTORE_WAIT_DOC",
    "DB_SET_INTERVAL",
    "DB_SET_TARGET_ID",
    "DEBT_LABELS",
    "DEBT_PAGE_SIZE",
    "DEFAULT_CURRENCY",
    "DL_DATE_G",
    "DL_DATE_J",
    "DL_DATE_MENU",
    "DT_AMOUNT",
    "DT_DIR",
    "DT_DUE",
    "DT_NOTE",
    "DT_PERSON",
    "ED_AMOUNT",
    "ED_DATE_G",
    "ED_DATE_J",
    "ED_DATE_MENU",
    "ED_DESC",
    "INSTALLMENT_NAME",
    "JMONTHS",
    "JOB_BACKUP",
    "JOB_DIGEST",
    "JOB_RECURRING",
    "LN_AMOUNT",
    "LN_COUNT",
    "LN_START",
    "LN_TITLE",
    "LOAN_PAGE_SIZE",
    "MIGRATIONS",
    "PERIOD_LABELS",
    "PRIMARY_ADMIN_USER_ID",
    "PRIMARY_ADMIN_USER_ID_RAW",
    "PROJECT_NAME",
    "PUBLIC_MAX_CATEGORIES",
    "PUBLIC_MAX_TX_PER_DAY",
    "RCP_WAIT",
    "RC_AMOUNT",
    "RC_CAT",
    "RC_DESC",
    "RC_PERIOD",
    "RC_START",
    "RC_TTYPE",
    "RG_END",
    "RG_START",
    "RLM",
    "RM_DAYS",
    "RM_HOUR",
    "SCHEMA_VERSION",
    "SEARCH_PAGE_SIZE",
    "SECTION_ORDER",
    "SR_QUERY",
    "TOP_CATEGORIES",
    "TREND_METRICS",
    "TX_AMOUNT",
    "TX_CAT_ADD_NAME",
    "TX_CAT_PICK",
    "TX_DATE_G",
    "TX_DATE_J",
    "TX_DATE_MENU",
    "TX_DESC",
    "TX_SNAPSHOT_FIELDS",
    "TX_TTYPE",
    "TZ",
    "ZWSP",
    "_INSTALLMENT_READY",
    "_SETTINGS_CACHE",
    "_columns",
    "_detect_version",
    "_table_exists",
    "_table_sql",
    "access_allowed",
    "access_cb",
    "access_menu",
    "add_jalali_months",
    "adm_add_name",
    "adm_add_uid",
    "admin_panel_cb",
    "apply_tx_date",
    "back_to_period_kb",
    "backup_filename",
    "backup_job",
    "breakdown_text",
    "budget_amount_input",
    "budget_catname_input",
    "budget_pick_kb",
    "budget_status",
    "budget_warning",
    "budgets_cb",
    "budgets_kb",
    "budgets_text",
    "build_admin_panel_kb",
    "build_app",
    "build_cat_kb",
    "cancel_cmd",
    "cat_add_name",
    "cat_pick_keyboard",
    "cat_rename_name",
    "category_breakdown",
    "cats_cb",
    "cats_root_menu",
    "comparison_lines",
    "count_transactions",
    "create_debt",
    "create_loan",
    "create_recurring",
    "csv_filename",
    "currency",
    "currency_cb",
    "currency_custom_input",
    "currency_kb",
    "current_pages",
    "daily_back_cb",
    "daily_cb",
    "daily_list_text",
    "daily_pick_menu",
    "daily_rows_kb",
    "db",
    "db_cb",
    "db_conn",
    "db_interval_entry",
    "db_menu_kb",
    "db_menu_text",
    "db_restore_entry",
    "db_restore_wait_doc",
    "db_set_interval_input",
    "db_set_target_id_input",
    "db_sidecars",
    "db_target_choice_cb",
    "db_target_kb",
    "debt_amount_input",
    "debt_dir_cb",
    "debt_dir_kb",
    "debt_due_input",
    "debt_due_skip",
    "debt_note_input",
    "debt_note_skip",
    "debt_person_input",
    "debt_totals",
    "debts_cb",
    "debts_kb",
    "debts_text",
    "delete_budget",
    "delete_debt",
    "delete_loan",
    "delete_recurring",
    "denied_text",
    "deny",
    "digest_job",
    "digest_text",
    "dl_date_g_input",
    "dl_date_j_input",
    "drop_sidecars",
    "dtx_cb",
    "ed_date_menu_kb",
    "edit_amount_input",
    "edit_date_g_input",
    "edit_date_j_input",
    "edit_date_menu_cb",
    "edit_desc_input",
    "ensure_installment",
    "fetch_cats",
    "finalize_tx",
    "find_categories_by_name",
    "fmt_money",
    "fmt_num",
    "g_to_j",
    "g_to_j_parts",
    "get_loan",
    "get_setting",
    "get_tx",
    "grp_label",
    "ikb",
    "init_db",
    "is_admin",
    "is_primary_admin",
    "j_month_range_g",
    "j_to_g_str",
    "j_year_range_g",
    "jalali_years_with_data",
    "jmonth_name",
    "list_budgets",
    "list_debts",
    "list_loans",
    "list_recurring",
    "loan_amount_input",
    "loan_count_input",
    "loan_detail_kb",
    "loan_detail_text",
    "loan_due_dates",
    "loan_progress",
    "loan_start_input",
    "loan_title_input",
    "loans_cb",
    "loans_kb",
    "loans_text",
    "logger",
    "main",
    "main_cb",
    "main_menu",
    "make_backup_bytes",
    "make_csv_bytes",
    "monthly_trend",
    "next_run_after",
    "next_unpaid_due",
    "normalize_pages",
    "now_ts",
    "on_error",
    "page_nav_row",
    "parse_amount",
    "parse_date_any",
    "parse_gregorian",
    "parse_jalali_to_g",
    "parse_period",
    "parse_quick_entry",
    "period_extra_kb",
    "previous_period",
    "quick_entry",
    "quick_entry_cb",
    "quick_group_kb",
    "range_end_input",
    "range_entry",
    "range_report_kb",
    "range_start_input",
    "rc_amount_input",
    "rc_cat_input",
    "rc_desc_input",
    "rc_desc_skip",
    "rc_period_cb",
    "rc_period_kb",
    "rc_start_input",
    "rc_ttype_cb",
    "rc_ttype_kb",
    "receipt_wait",
    "record_loan_payment",
    "recurring_cb",
    "recurring_job",
    "recurring_kb",
    "recurring_text",
    "remember_pages",
    "reminder_days_input",
    "reminder_hour_input",
    "reminders_cb",
    "reminders_kb",
    "reminders_text",
    "report_cb",
    "report_lines",
    "report_month_kb",
    "report_root",
    "report_root_kb",
    "report_year_kb",
    "resolve_scope_owner",
    "restore_tx",
    "rtl",
    "run_due_recurring",
    "safe_edit",
    "save_disk_backup",
    "save_quick_entry",
    "schedule_backup_job",
    "schedule_digest_job",
    "schedule_recurring_job",
    "search_entry",
    "search_page_cb",
    "search_query_input",
    "search_results_kb",
    "search_results_text",
    "search_transactions",
    "send_backup_file",
    "set_budget",
    "set_receipt",
    "set_setting",
    "settings_cb",
    "settings_menu",
    "settle_debt",
    "setup_commands",
    "show_search_results",
    "snapshot_tx",
    "start",
    "start_text",
    "sums_all",
    "sums_for_range",
    "to_ascii_digits",
    "today_g",
    "toggle_recurring",
    "trend_cb",
    "trend_kb",
    "trend_text",
    "ttype_label",
    "tx_amount_input",
    "tx_cat_add_name_input",
    "tx_cat_change_kb",
    "tx_cat_pick_cb",
    "tx_date_g_input",
    "tx_date_j_input",
    "tx_date_menu_cb",
    "tx_date_menu_kb",
    "tx_desc_input",
    "tx_desc_skip",
    "tx_detail_text",
    "tx_entry_from_daily",
    "tx_entry_from_menu",
    "tx_menu",
    "tx_ttype_cb",
    "tx_ttype_kb",
    "tx_view_kb",
    "unknown_callback",
    "upcoming_loan_reminders",
    "validate_backup_file",
    "week_range_g",
    "within_quota",
]
